notifications:
  slack:
    secure: PU4jH8A1V6/naRID4YVfJ+rJZ6F+NzMMYewDd997P/CNR6epHU8cy5PSbZExb1hs+TbYqj88jy2DxwBxGZdMds022VROPV/B2WaMfho2lSLvLPSqx/GzVJT8F+uMgI/A55IYG1MTuKFN37t1oNrH9Iq07GiVsaBwRFXJ+eVaZ50=
language: python
python:
  - "3.5"

addons:
  apt:
    packages:
    - glpk-utils

before_install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install flake8-future-import

install:
  - python setup.py install

script:
  - flake8 .
  - py.test -v tests
